### ISSUE TITLE
Accept capital letter inputs to recommend command

### ISSUE THREAD

**Issue by aticie** [goeo-/memebot-2.0#3]
Just change regex so that it also accepts !R, currently it says no such command. 

![image](https://user-images.githubusercontent.com/25616662/101535525-d58d5e00-39a9-11eb-9306-2ff8bb4204ed.png)

Edit: or just change this line https://github.com/goeo-/memebot-2.0/blob/d4a1b1ec55d8937ed3d4a4bfdc6e98d16418ab89/handlers/command.py#L28 to:

`if regex_.match(message.lower()):`

**Comment by Lemmmy** [comment]
Sounds useful; I would probably do it by adding `(?i)` to the regular expressions themselves:

https://github.com/goeo-/memebot-2.0/blob/d4a1b1ec55d8937ed3d4a4bfdc6e98d16418ab89/handlers/command.py#L7-L10

Would you like to submit a PR?

**Comment by aticie** [comment]
nah fam just change it. it's only 1 line or something
