### ISSUE TITLE
idk if this is really an issue but

### ISSUE THREAD

**Issue by cheesec4ke** [goeo-/memebot-2.0#7]
the bot recommended the big black and then a map from 2011

**Comment by cheesec4ke** [comment]
in fact it seems to only recommend maps from 2011

**Comment by MaxKruse** [comment]
this is optimal

**Comment by goeo-** [comment]
this is very weird. the database most definitely has newer maps than that - probably has to do with the bot's perception of your profile. will investigate.

**Comment by cheesec4ke** [comment]
if it helps, my profile is [here](https://osu.ppy.sh/users/17091039)

**Comment by cheesec4ke** [comment]
just tried to use the bot and this is still an issue

**Comment by mayacopeland** [comment]
Wontfix.

**Comment by goeo-** [comment]
hey sorry i forgor that we fixed this, the database had killed itself
